server:
  port: 8848
  servlet:
    context-path: /xiaozhi
    jsp:
      init-parameters:
        development: true #开启jsp热部署
spring:
  banner:
    charset: UTF-8
    image:
      location: classpath:banner.jpg
  mvc: #视图解析器
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xiaozhi?useUnicode=true&characterEncoding=utf8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  type-aliases-package: com.baizhi.entity #起别名
  mapper-locations: classpath:mapper/*Mapper.xml